### PR TITLE
ci: switches to workflow codeql

### PR DESCRIPTION
**Pull request by baywet**
since the configured one doesn't trigger on anything else than cs file modifications and blocks the checks

### CODE REVIEW

**Comment by andreaTP** [comment]
Thanks for opening this PR Vincent!
I'm unsure about the motivation for having CodeQL just for C# in this submodule though...

Would you mind sharing?
Additional notes:
- why not adding it to the main repo?
- why keeping additional configuration for e.g. swift?
- why a nightly check?

**Review by andreaTP — CHANGES_REQUESTED** [review]
A few questions to better understand the scope and context of this PR.

**Comment by baywet** [comment]
Hey Andrea, 
This can wait when you're back at work. 
But to answer your questions: 
- code ql rules are added continuously, the general recommendation is to run the analysis on regular bases even if there are few code changes.
- that was the default template, I made as few changes as possible. But I can clean it up if you want. 
- as far as I understand the tool and its interface, it's usually easier to have a more focused approach per language instead of mixing things. It'll also be easier to demonstrate we're "compliant" for dotnet. (Codeql became a requirement for Microsoft owned repositories a while ago, I wouldn't be surprised if the dotnet foundation requires the same)

**Comment by andreaTP** [comment]
> This can wait when you're back at work.

Cool, I think I'd prefer a consistent setup across languages but let's discuss in a couple of weeks ;-)

**Comment by andreaTP** [comment]
> This can wait when you're back at work.

Back, catching up :slightly_smiling_face: 

I'm ok adding CodeQL checks to the `std-uritemplate` repo, looks like a good improvement, a few suggestions to land this effort:

- enable it only on schedule (the proposed run once a week is fine by me)
- the check should be performed in the [main](https://github.com/std-uritemplate/std-uritemplate) repo
- if necessary, we can split the execution in multiple `jobs`

thoughts @baywet ?

**Comment by baywet** [comment]
Welcome back!

> enable it only on schedule

Our security and compliance team requires it on PRs as well. Reasoning being you don't want to accept changes that introduce vulnerabilities. I'm not saying we have to follow those requirements to the letter, but the rationale makes sense to me.

> the check should be performed in the [main](https://github.com/std-uritemplate/std-uritemplate) repo

For the reason above, and since the code "lives" here for dotnet, I think it makes more sense to have the dotnet one here. For the other languages I have no objection.

> if necessary, we can split the execution in multiple jobs

Sure.

**Comment by andreaTP** [comment]
Have you considered a re-usable workflow defined in the main repo and re-used here?

Sorry for bothering ... but I know by a fact that I'm going to forget quickly about those nuances ...

**Comment by baywet** [comment]
The challenge is the path will change and require scripting. But we can leave a big comment in the codeql of the main repo that points to this one?

**Comment by andreaTP** [comment]
> The challenge is the path will change and require scripting.

Ok, I'm convinced we can live with two implementations, would you mind cleaning up the script to be tight to the repo (e.g. remove Swift reverences, matrix etc.)?

**Comment by baywet** [comment]
> cleaning up the script to be tight to the repo (e.g. remove Swift reverences, matrix etc.)?
done

**Review by andreaTP — APPROVED** [review]
Cool! Thanks!

**Pull request merged**
